"""Catálogo das 26 críticas oficiais de pós-processamento."""

from __future__ import annotations

from src.config import (
    POST_PROCESSING_CRITICS_PATH,
)
from src.domain.post_processing import (
    PostProcessingExecutionClass,
    PostProcessingProvider,
    PostProcessingRuleDefinition,
)


def _rule(
    code: str,
    official_type: str,
    description: str,
    evaluated_fields: str,
    observations: str,
    scope: str,
    execution_class: PostProcessingExecutionClass,
    dependency: str | None,
    provider: PostProcessingProvider,
    source_rule_code: str | None = None,
) -> PostProcessingRuleDefinition:
    return PostProcessingRuleDefinition(
        code=code,
        official_type=official_type,
        official_description=description,
        evaluated_fields=evaluated_fields,
        observations=observations,
        scope=scope,
        execution_class=execution_class,
        dependency=dependency,
        provider=provider,
        source_path=POST_PROCESSING_CRITICS_PATH,
        source_rule_code=source_rule_code,
    )


POST_PROCESSING_RULES: tuple[
    PostProcessingRuleDefinition,
    ...,
] = (
    _rule(
        "DRO000001",
        "Inconsistência",
        "Verifica, em cada categoria do Bloco 2 - Eventos Consolidados, se a perda bruta acumulada no semestre é, em média, superior ao limite de R$ 1.000,00.",
        "(perdaEfetivaSemestreConsol + provisaoSemestreConsol) / numEventosSemestreConsol > 1000",
        "Eventos com perda bruta superior a R$ 1.000,00 devem ser informados no Bloco 1 - Eventos Individualizados.",
        "EVENTO_CONSOLIDADO",
        PostProcessingExecutionClass.CONSOLIDATED,
        "Cálculo determinístico dos eventos consolidados",
        PostProcessingProvider.CONSOLIDATED,
    ),
    _rule(
        "DRO000002",
        "Inconsistência",
        "Verifica, em cada categoria do Bloco 2 - Eventos Consolidados, se a perda bruta acumulada é, em média, superior ao limite de R$ 1.000,00.",
        "(perdaEfetivaTotalConsol + provisaoTotalConsol) / numEventosTotalConsol > 1000",
        "Eventos com perda bruta superior a R$ 1.000,00 devem ser informados no Bloco 1 - Eventos Individualizados.",
        "EVENTO_CONSOLIDADO",
        PostProcessingExecutionClass.CONSOLIDATED,
        "Cálculo determinístico dos eventos consolidados",
        PostProcessingProvider.CONSOLIDATED,
    ),
    _rule(
        "DRO000003",
        "Inconsistência",
        "Contingências passivas ocorridas após 01/01/2021, avaliadas individualmente, sem detalhamento de probabilidade de perda.",
        "tipoAvaliacao; probabilidadePerda; valorRisco; dataOcorrencia",
        "O detalhamento das probabilidades de perda é obrigatório para contingências passivas avaliadas individualmente.",
        "EVENTO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.CUSTOM_EVENT,
    ),
    _rule(
        "DRO000004",
        "Inconsistência",
        "Contingências passivas, avaliadas individualmente, com atribuição de perda provável e sem atribuição de provisão.",
        'tipoAvaliacao = "I" e probabilidadePerda = "PR" e totalProvisao = 0',
        "Conforme CPC-25, contingências avaliadas como perdas prováveis devem ser provisionadas.",
        "EVENTO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.CUSTOM_EVENT,
    ),
    _rule(
        "DRO000005",
        "Inconsistência",
        "Contingências passivas, avaliadas individualmente, com atribuição de perda possível ou remorta e sem atribuição do valor do risco da contingência.",
        'tipoAvaliacao = "I" e probabilidadePerda = "PO" ou "RE" e valorRisco = 0',
        "O valor em risco deve ser informado no detalhamento de probabilidade de perdas.",
        "EVENTO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.CUSTOM_EVENT,
    ),
    _rule(
        "DRO000009",
        "Inconsistência",
        "Eventos posteriores a 01/01/2021 sem atribuição do 2º Nível de Classificação Basileia II.",
        "min(dataContabilizacao) > 01/01/2021 e categoriaNivel2 = ?",
        "Campo obrigatório para eventos ocorridos após 01/01/2021.",
        "EVENTO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.CUSTOM_EVENT,
    ),
    _rule(
        "DRO000010",
        "Inconsistência",
        "Eventos com contabilizações anteriores à data de descoberta.",
        "dataContabilizacao < dataDescoberta",
        "Não é esperado que haja contabilização antes da própria descoberta do evento de perda operacional.",
        "CONTABILIZACAO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.ROW_VALIDATION,
        "BASE-CONT-DATA-001",
    ),
    _rule(
        "DRO000011",
        "Inconsistência",
        "Eventos com valor total de perda efetiva com sinal negativo.",
        "totalPerdaEfetiva < -10",
        "Perdas efetivas devem ser lançadas com valores positivos. Eventuais estornos não devem ultrapassar o próprio valor da perda.",
        "EVENTO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.EVENT_FINANCIAL,
        "DRO000011",
    ),
    _rule(
        "DRO000012",
        "Inconsistência",
        "Eventos com valor total de provisão com sinal negativo.",
        "totalProvisao < -10",
        "Provisões devem ser lançadas com valores positivos. Eventuais estornos não devem ultrapassar o próprio valor da provisão.",
        "EVENTO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.EVENT_FINANCIAL,
        "DRO000012",
    ),
    _rule(
        "DRO000013",
        "Inconsistência",
        "Eventos com valor total recuperado com sinal positivo.",
        "totalRecuperado > 0",
        "Convenção é de valor negativo para a recuperação.",
        "EVENTO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.EVENT_FINANCIAL,
        "DRO000013",
    ),
    _rule(
        "DRO000014",
        "Inconsistência",
        "Eventos com valor total recuperado, em módulo, superior ao valor da perda bruta.",
        "abs(totalRecuperado) > totalPerdaEfetiva + totalProvisao",
        "A recuperação de perdas não pode superar o valor da perda bruta.",
        "EVENTO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.EVENT_FINANCIAL,
        "DRO000014",
    ),
    _rule(
        "DRO000015",
        "Inconsistência",
        "Inconsistência entre os totais de Perda Efetiva, Provisão ou Valor Recuperado e a soma do bloco de contabilizações.",
        "totalPerdaEfetiva ≠ soma(valorPerdaEfetiva) ou totalProvisao ≠ soma(valorProvisao) ou totalRecuperado ≠ soma(valorRecuperado)",
        "Os valores totais devem corresponder à soma dos lançamentos parciais.",
        "EVENTO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.EVENT_FINANCIAL,
        "DRO000015",
    ),
    _rule(
        "DRO000016",
        "Inconsistência",
        "Existência de eventos que não estão informados na data-base e que foram informados em data-base imediatamente anterior.",
        "idEvento, max(dataContabilizacao), dataBase",
        "Não é esperado que haja migração de quantidade significativa de eventos do Bloco 1 - Eventos Individualizados para o Bloco 2 - Eventos Consolidados.",
        "HISTORICO",
        PostProcessingExecutionClass.HISTORICAL,
        "Documento 5050 da data-base imediatamente anterior",
        PostProcessingProvider.HISTORICAL,
    ),
    _rule(
        "DRO000017",
        "Inconsistência",
        "Indícios de eventos que não constam na data-base imediante anterior e que deveriam ter sido informados.",
        "totalPerdaEfetiva + totalProvisao; dataContabilizacao; dataDescoberta",
        "Eventos que ocorreram e que tiveram contabilizações em data anterior ao fechamento da data-base anterior, mas não foram informados no DRO correspondente.",
        "HISTORICO",
        PostProcessingExecutionClass.HISTORICAL,
        "Documento 5050 da data-base imediatamente anterior",
        PostProcessingProvider.HISTORICAL,
    ),
    _rule(
        "DRO000018",
        "Inconsistência",
        "Verifica a existência de perda efetiva negativa em cada categoria do Bloco 2 - Eventos Consolidados.",
        "perdaEfetivaTotalConsol < -10",
        "Perdas efetivas devem ser lançadas com valores positivos. Eventuais estornos não devem ultrapassar o próprio valor da perda.",
        "EVENTO_CONSOLIDADO",
        PostProcessingExecutionClass.CONSOLIDATED,
        "Cálculo determinístico dos eventos consolidados",
        PostProcessingProvider.CONSOLIDATED,
    ),
    _rule(
        "DRO000019",
        "Inconsistência",
        "Verifica a existência de provisão negativa em cada categoria do Bloco 2 - Eventos Consolidados.",
        "provisaoTotalConsol < -10",
        "Provisões devem ser lançadas com valores positivos. Eventuais estornos não devem ultrapassar o próprio valor da provisão.",
        "EVENTO_CONSOLIDADO",
        PostProcessingExecutionClass.CONSOLIDATED,
        "Cálculo determinístico dos eventos consolidados",
        PostProcessingProvider.CONSOLIDATED,
    ),
    _rule(
        "DRO000021",
        "Inconsistência",
        "Eventos com atribuição de 2º Nível de Classificação Basileia II incondizente com 1º Nível",
        "categoriaNivel1 e categoriaNivel2",
        "Os níveis de classificação de Basileia II estão associados. Por exemplo, um evento de 1º Nível: 2 e 2º Nível: 71 é inconsistente.",
        "EVENTO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.ROW_VALIDATION,
        "BASE-REL-CAT-001",
    ),
    _rule(
        "DRO000022",
        "Inconsistência",
        "Eventos que apresentam redução de Perda Efetiva com relação à data-base imediatamente anterior",
        "totalPerdaEfetiva; dataBase",
        "Não é esperado que haja quantidade significativa de eventos com estorno de perdas efetivas.",
        "HISTORICO",
        PostProcessingExecutionClass.HISTORICAL,
        "Documento 5050 da data-base imediatamente anterior",
        PostProcessingProvider.HISTORICAL,
    ),
    _rule(
        "DRO000023",
        "Inconsistência",
        "Verifica a existência momentânea de saldo acumulado negativo de Perda Efetiva, no bloco de contabilizações.",
        "valorPerda; dataContabilizacao",
        "Perdas efetivas devem ser lançadas com valores positivos. Eventuais estornos não devem ultrapassar o próprio valor da perda.",
        "CONTABILIZACAO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.EVENT_FINANCIAL,
        "DRO000023",
    ),
    _rule(
        "DRO000024",
        "Esclarecimento",
        "Verifica a existência momentânea de saldo acumulado negativo de Provisão, no bloco de contabilizações.",
        "valorProvisao; dataContabilizacao",
        "Provisões devem ser lançadas com valores positivos. Eventuais estornos não devem ultrapassar o próprio valor da provisão.",
        "CONTABILIZACAO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.EVENT_FINANCIAL,
        "DRO000024",
    ),
    _rule(
        "DRO000026",
        "Esclarecimento",
        "Verifica alterações indevidas no bloco de contabilizações, em comparação à data-base imediatamente anterior.",
        "valorPerda; valorProvisao; valorRecuperado; dataContabilizacao; dataBase",
        "Não é esperado que haja qualquer alteração no histórico dos lançamentos contábeis de um evento até a data de fechamento da data-base anterior.",
        "HISTORICO",
        PostProcessingExecutionClass.HISTORICAL,
        "Documento 5050 da data-base imediatamente anterior",
        PostProcessingProvider.HISTORICAL,
    ),
    _rule(
        "DRO000027",
        "Esclarecimento",
        "Eventos com alteração da natureza da contingência, em compração à data-base imediatamente anterior.",
        "naturezaContingencia em dataBase atual ≠ naturezaContingencia em dataBase anterior",
        "Não é esperado que haja quantidade significativa de alteração na classificação da natureza do evento.",
        "HISTORICO",
        PostProcessingExecutionClass.HISTORICAL,
        "Documento 5050 da data-base imediatamente anterior",
        PostProcessingProvider.HISTORICAL,
    ),
    _rule(
        "DRO000028",
        "Esclarecimento",
        "Eventos com alteração na avaliação de risco associado, em compração à data-base imediatamente anterior.",
        "riscoAssociado em dataBase atual ≠ riscoAssociado em dataBase anterior",
        "Não é esperado que haja quantidade significativa de alteração na classificação de risco associado.",
        "HISTORICO",
        PostProcessingExecutionClass.HISTORICAL,
        "Documento 5050 da data-base imediatamente anterior",
        PostProcessingProvider.HISTORICAL,
    ),
    _rule(
        "DRO000029",
        "Esclarecimento",
        "Eventos com alteração na avaliação de associação ao risco cibernético, em compração à data-base imediatamente anterior.",
        "ligadoRiscoCibernetico em dataBase atual ≠ ligadoRiscoCibernetico em dataBase anterior",
        "Não é esperado que haja quantidade significativa de alteração na classificação associação ao risco cibernético.",
        "HISTORICO",
        PostProcessingExecutionClass.HISTORICAL,
        "Documento 5050 da data-base imediatamente anterior",
        PostProcessingProvider.HISTORICAL,
    ),
    _rule(
        "DRO000030",
        "Esclarecimento",
        "Eventos com alteração na avaliação de associação ao risco socioambiental, em compração à data-base imediatamente anterior.",
        "ligadoRiscoSocioAmbiental em dataBase atual ≠ ligadoRiscoSocioAmbiental em dataBase anterior",
        "Não é esperado que haja quantidade significativa de alteração na classificação associação ao risco socioambiental.",
        "HISTORICO",
        PostProcessingExecutionClass.HISTORICAL,
        "Documento 5050 da data-base imediatamente anterior",
        PostProcessingProvider.HISTORICAL,
    ),
    _rule(
        "DRO000032",
        "Inconsistência",
        "Eventos de fraude (categorias 1 e 2 do 1º Nível de Classificação Basileia II) com provisão.",
        "categoriaNivel1 = 1 ou 2 e totalProvisao > 0",
        "Principiologicamente, não é esperado que haja provisão para eventos de fraude.",
        "EVENTO",
        PostProcessingExecutionClass.LOCAL,
        None,
        PostProcessingProvider.CUSTOM_EVENT,
    ),
)


POST_PROCESSING_CODES: tuple[str, ...] = tuple(
    rule.code
    for rule in POST_PROCESSING_RULES
)


def get_post_processing_rule(
    code: str,
) -> PostProcessingRuleDefinition:
    for rule in POST_PROCESSING_RULES:
        if rule.code == code:
            return rule

    raise KeyError(
        "Crítica de pós-processamento "
        f"não catalogada: {code}"
    )
