"""Entidades e objetos de domínio do Documento 5050."""

from src.domain.base_row import (
    BaseRowIssue,
    BaseRowsNormalizationResult,
    NormalizedBaseField,
    NormalizedBaseRow,
)
from src.domain.base_row_validation import (
    BaseRowKind,
    BaseRowValidationResult,
    BaseRowsValidationResult,
    RowRuleResult,
    RuleExecutionStatus,
)
from src.domain.document_header import DocumentHeader
from src.domain.document_model import (
    DocumentBuildIssue,
    DocumentBuildResult,
    FinalAccounting,
    FinalConsolidatedEvent,
    FinalDocument,
    FinalIndividualEvent,
    FinalInternalAccount,
    FinalProbability,
    FinalSourceSystem,
    UnsupportedProfileValue,
)
from src.domain.event_financial import (
    AccountingDayBalance,
    EventFinancialSummary,
    EventFinancialValidationResult,
    EventsFinancialValidationResult,
)
from src.domain.event_classification import (
    ConsolidatedCalculationResult,
    EventClassification,
    EventClassificationResult,
    EventDestination,
)
from src.domain.grouped_event import (
    EventGroupingResult,
    EventRuleResult,
    EventValidationResult,
    EventsValidationResult,
    GroupedAccounting,
    GroupedEvent,
    GroupedProbability,
    ResolvedEventField,
)
from src.domain.normalization import (
    NormalizationResult,
    NormalizationStatus,
)
from src.domain.post_processing import (
    PostProcessingEvidence,
    PostProcessingExecutionClass,
    PostProcessingProvider,
    PostProcessingRuleDefinition,
    PostProcessingRuleResult,
    PostProcessingValidationResult,
)
from src.domain.pre_processing import (
    PreProcessingEvidence,
    PreProcessingExecutionClass,
    PreProcessingProvider,
    PreProcessingRuleDefinition,
    PreProcessingRuleResult,
    PreProcessingValidationResult,
)
from src.domain.reporting import (
    ExternalValidationStatus,
    ExecutionReportData,
    FinalExecutionStatus,
    FinalValidationStatus,
    HistoricalValidationStatus,
    LocalValidationStatus,
    ReportArtifacts,
    ReportGenerationIssue,
    ReportGenerationResult,
    ReportRecord,
    ReportRuleSummary,
    XsdValidationSummaryStatus,
)
from src.domain.rule_reconciliation import (
    RuleReconciliationRecord,
    RuleReconciliationResult,
)
from src.domain.conversion import (
    ConversionArtifacts,
    ConversionIssue,
    ConversionRequest,
    ConversionResult,
    ConversionStage,
    ConversionStageRecord,
    ConversionStageStatus,
    FinalStatusDecision,
    FinalStatusReason,
    freeze_stage_outputs,
)
from src.domain.reference_tables import (
    ReferenceTableData,
    ReferenceTableKind,
    ReferenceTableRecord,
    ReferenceTableRuleResult,
    ReferenceTablesReadResult,
    ReferenceTablesValidationResult,
)
from src.domain.xsd_validation import (
    XsdValidationIssue,
    XsdValidationResult,
    XsdValidationStatus,
)
from src.domain.xml_generation import (
    XmlElementCounts,
    XmlGenerationIssue,
    XmlGenerationMode,
    XmlGenerationResult,
)
from src.domain.regulatory_version import (
    RegulatoryVersion,
    VersionStatus,
    YearMonth,
)

__all__ = [
    "AccountingDayBalance",
    "BaseRowIssue",
    "BaseRowKind",
    "BaseRowValidationResult",
    "BaseRowsNormalizationResult",
    "BaseRowsValidationResult",
    "ConsolidatedCalculationResult",
    "DocumentHeader",
    "DocumentBuildIssue",
    "DocumentBuildResult",
    "FinalAccounting",
    "FinalConsolidatedEvent",
    "FinalDocument",
    "FinalIndividualEvent",
    "FinalInternalAccount",
    "FinalProbability",
    "FinalSourceSystem",
    "UnsupportedProfileValue",
    "EventFinancialSummary",
    "EventClassification",
    "EventClassificationResult",
    "EventDestination",
    "EventFinancialValidationResult",
    "EventGroupingResult",
    "EventRuleResult",
    "EventValidationResult",
    "EventsFinancialValidationResult",
    "EventsValidationResult",
    "GroupedAccounting",
    "GroupedEvent",
    "GroupedProbability",
    "NormalizedBaseField",
    "NormalizedBaseRow",
    "NormalizationResult",
    "NormalizationStatus",
    "ConversionArtifacts",
    "ConversionIssue",
    "ConversionRequest",
    "ConversionResult",
    "ConversionStage",
    "ConversionStageRecord",
    "ConversionStageStatus",
    "FinalStatusDecision",
    "FinalStatusReason",
    "freeze_stage_outputs",
    "ExecutionReportData",
    "ExternalValidationStatus",
    "FinalExecutionStatus",
    "FinalValidationStatus",
    "HistoricalValidationStatus",
    "LocalValidationStatus",
    "ReportArtifacts",
    "ReportGenerationIssue",
    "ReportGenerationResult",
    "ReportRecord",
    "ReportRuleSummary",
    "RuleReconciliationRecord",
    "RuleReconciliationResult",
    "XsdValidationSummaryStatus",
    "ReferenceTableData",
    "ReferenceTableKind",
    "ReferenceTableRecord",
    "ReferenceTableRuleResult",
    "ReferenceTablesReadResult",
    "ReferenceTablesValidationResult",
    "PostProcessingEvidence",
    "PostProcessingExecutionClass",
    "PostProcessingProvider",
    "PostProcessingRuleDefinition",
    "PostProcessingRuleResult",
    "PostProcessingValidationResult",
    "PreProcessingEvidence",
    "PreProcessingExecutionClass",
    "PreProcessingProvider",
    "PreProcessingRuleDefinition",
    "PreProcessingRuleResult",
    "PreProcessingValidationResult",
    "RegulatoryVersion",
    "ResolvedEventField",
    "RowRuleResult",
    "RuleExecutionStatus",
    "VersionStatus",
    "XsdValidationIssue",
    "XsdValidationResult",
    "XsdValidationStatus",
    "XmlElementCounts",
    "XmlGenerationIssue",
    "XmlGenerationMode",
    "XmlGenerationResult",
    "YearMonth",
]
